const now = new Date();

function daysAgo(days) {
  return new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();
}

export const mockProducts = [
  {
    id: "a6e4f4f8-4af8-4f48-9d92-1d3f8f2c1a01",
    name: "Cuaderno profesional cuadriculado",
    sku: "LAP-CUA-001",
    description: "Cuaderno tamaño profesional con 100 hojas, pasta dura y cuadriculado fino.",
    category: "Cuadernos",
    brand: "Scribe",
    price: 89.9,
    stock: 24,
    imageUrl: "/products/cuaderno.jpg",
    isActive: true,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(2),
  },
  {
    id: "0b8ab7ce-99e7-4497-96ad-e0c58cdfe102",
    name: "Colores de madera 24 piezas",
    sku: "LAP-COL-024",
    description: "Caja de colores intensos para uso escolar y creativo.",
    category: "Arte",
    brand: "Maped",
    price: 169,
    stock: 12,
    imageUrl: "/products/colores.webp",
    isActive: true,
    createdAt: daysAgo(21),
    updatedAt: daysAgo(5),
  },
  {
    id: "4e49ee42-1c87-4234-a614-f1b9e88b3103",
    name: "Marcadores permanentes 5 piezas",
    sku: "LAP-MAR-005",
    description: "Marcadores resistentes para cartón, papel y plástico.",
    category: "Escritura",
    brand: "Sharpie",
    price: 75,
    stock: 6,
    imageUrl: "/products/marcadores.webp",
    isActive: true,
    createdAt: daysAgo(32),
    updatedAt: daysAgo(4),
  },
  {
    id: "9f44cbbf-7548-4b73-9551-2e70e5235c04",
    name: "Pegamento blanco escolar 125 g",
    sku: "LAP-PEG-125",
    description: "Pegamento lavable ideal para tareas y manualidades.",
    category: "Manualidades",
    brand: "Resistol",
    price: 38.5,
    stock: 0,
    imageUrl: "/products/resistol.webp",
    isActive: false,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(18),
  },
  {
    id: "16dbfbd7-2b17-46fa-a66d-92d4e49d1205",
    name: "Cartulina iris surtida",
    sku: "LAP-CAR-IRIS",
    description: "Paquete con cartulinas de colores surtidos para proyectos escolares.",
    category: "Papeles",
    brand: "Pochteca",
    price: 58,
    stock: 31,
    imageUrl: "",
    isActive: true,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
  },
  {
    id: "537dcc33-c487-47f7-8a0a-36eeb22b5e06",
    name: "Lápices HB 12 piezas",
    sku: "LAP-LAP-012",
    description: "Caja escolar con mina resistente y borrador incluido.",
    category: "Escritura",
    brand: "BIC",
    price: 79,
    stock: 8,
    imageUrl: "/products/lapices.jpg",
    isActive: true,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(7),
  },
  {
    id: "7c03cab0-c300-4af0-ab70-c92185f51a07",
    name: "Carpeta tamaño carta con broche",
    sku: "LAP-CAR-CTA",
    description: "Carpeta plástica para documentos y tareas.",
    category: "Oficina",
    brand: "Acco",
    price: 32,
    stock: 15,
    imageUrl: "",
    isActive: true,
    createdAt: daysAgo(17),
    updatedAt: daysAgo(6),
  },
  {
    id: "8746cd25-1e08-4dc4-9c28-6d6a15876308",
    name: "Juego geométrico escolar",
    sku: "LAP-GEO-001",
    description: "Set con regla, escuadras y transportador.",
    category: "Escolar",
    brand: "Maped",
    price: 18,
    stock: 4,
    imageUrl: "/products/juego_geometrico.jpg",
    isActive: true,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(9),
  },
  {
    id: "be3c2a63-61d1-4cf5-9d00-9d5c537b3309",
    name: "Tijeras junior punta roma",
    sku: "LAP-TIJ-JR",
    description: "Tijeras seguras para niños y uso escolar.",
    category: "Escolar",
    brand: "Maped",
    price: 55,
    stock: 11,
    imageUrl: "/products/tijeras.png",
    isActive: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(30),
  },
  {
    id: "72fa781c-d67d-4252-8267-d5f003f94510",
    name: "Plumones punta fina 10 piezas",
    sku: "LAP-PLU-010",
    description: "Set de plumones para lettering y trabajos creativos.",
    category: "Arte",
    brand: "Crayola",
    price: 129,
    stock: 19,
    imageUrl: "",
    isActive: true,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
];
